### ISSUE TITLE
Send shop URL when requesting module updates

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/ps_distributionapiclient#13]
Send shop URL in query string so that the project can track shops running on PS software.

A note stating this information retrieval can be added in README (cc @matks)

**Comment by matks** [comment]
Follow-up steps https://github.com/PrestaShop/PrestaShop/issues/31626
https://github.com/PrestaShop/PrestaShop/issues/31625
https://github.com/PrestaShop/PrestaShop/issues/31627

**Comment by matks** [comment]
And https://github.com/PrestaShop/PrestaShop/issues/31805
